begin;

select plan(28);

select has_table('public', 'conversation_webhook_attempt', 'sanitized webhook attempts exist');
select has_column('public', 'conversation_webhook_attempt', 'studio_id', 'attempt is scoped to a known studio');
select has_column('public', 'conversation_webhook_attempt', 'outcome', 'attempt stores a fixed outcome');
select has_column('public', 'conversation_webhook_attempt', 'received_at', 'attempt has a server timestamp');
select hasnt_column('public', 'conversation_webhook_attempt', 'content', 'attempt does not store message content');
select hasnt_column('public', 'conversation_webhook_attempt', 'payload', 'attempt does not store payload');
select hasnt_column('public', 'conversation_webhook_attempt', 'signature', 'attempt does not store signatures');
select hasnt_column('public', 'conversation_webhook_attempt', 'secret', 'attempt does not store secrets');
select hasnt_column('public', 'conversation_webhook_attempt', 'url', 'attempt does not store URLs');
select hasnt_column('public', 'conversation_webhook_attempt', 'connection_id', 'attempt does not store connection IDs');
select hasnt_column('public', 'conversation_webhook_attempt', 'delivery_id', 'attempt does not store delivery IDs');
select hasnt_column('public', 'conversation_webhook_attempt', 'external_account_id', 'attempt does not store account IDs');
select hasnt_column('public', 'conversation_webhook_attempt', 'external_inbox_id', 'attempt does not store inbox IDs');
select hasnt_column('public', 'conversation_webhook_attempt', 'external_conversation_id', 'attempt does not store conversation IDs');
select hasnt_column('public', 'conversation_webhook_attempt', 'external_message_id', 'attempt does not store message IDs');
select ok((select relrowsecurity from pg_class where oid = 'public.conversation_webhook_attempt'::regclass), 'attempt RLS is enabled');
select ok(has_table_privilege('service_role', 'public.conversation_webhook_attempt', 'select'), 'service role can inspect attempts');
select ok(not has_table_privilege('authenticated', 'public.conversation_webhook_attempt', 'select'), 'authenticated cannot inspect attempts');
select ok(not has_table_privilege('anon', 'public.conversation_webhook_attempt', 'insert'), 'anon cannot create attempts');
select ok(has_function_privilege('service_role', 'public.record_conversation_webhook_attempt(uuid,text,text)', 'execute'), 'service role records attempts');
select ok(not has_function_privilege('authenticated', 'public.record_conversation_webhook_attempt(uuid,text,text)', 'execute'), 'authenticated cannot record attempts');
select ok(not has_function_privilege('anon', 'public.record_conversation_webhook_attempt(uuid,text,text)', 'execute'), 'anon cannot record attempts');

set local role service_role;

select lives_ok(
  $$ select public.record_conversation_webhook_attempt('20000000-0000-0000-0000-000000000001', 'chatwoot', 'schema_invalid') $$,
  'service role records a sanitized rejected attempt'
);
select throws_ok(
  $$ select public.record_conversation_webhook_attempt('20000000-0000-0000-0000-000000000001', 'chatwoot', 'attacker-controlled') $$,
  '23514', null, 'outcome is restricted to fixed low-cardinality values'
);

select is(
  public.ingest_conversation_webhook('20000000-0000-0000-0000-000000000001', 'chatwoot', 'observability-delivery', 'message_created', '3', '7', '42', '84', '2026-10-05T08:00:00Z'),
  'ACCEPTED', 'accepted ingestion remains accepted'
);
select is(
  public.ingest_conversation_webhook('20000000-0000-0000-0000-000000000001', 'chatwoot', 'observability-delivery', 'message_created', '3', '7', '42', '84', '2026-10-05T08:00:00Z'),
  'DUPLICATE', 'duplicate ingestion remains duplicate'
);
select results_eq(
  $$ select outcome from public.conversation_webhook_attempt where studio_id = '20000000-0000-0000-0000-000000000001' order by id $$,
  $$ values ('schema_invalid'::text), ('accepted'::text), ('duplicate'::text) $$,
  'attempt history distinguishes rejected, accepted and duplicate outcomes without provider identifiers'
);
select ok(
  (select bool_and(received_at = current_timestamp) from public.conversation_webhook_attempt),
  'attempt timestamps are generated by the database server'
);

select * from finish();
rollback;
