begin;
select plan(18);
select has_table('public','free_choice_approval_operation','approval operation exists');
select ok((select relrowsecurity from pg_class where oid='public.free_choice_approval_operation'::regclass),'operation RLS enabled');
select ok(not has_table_privilege('anon','public.free_choice_approval_operation','select'),'anon cannot read operations');
select ok(not has_table_privilege('authenticated','public.free_choice_approval_operation','select'),'authenticated cannot read operations');
select ok(not has_table_privilege('service_role','public.free_choice_approval_operation','select'),'service role uses RPC only');
select col_type_is('public','appointment','source','appointment_source','appointment source is explicit');
select col_is_null('public','appointment','booking_offer_id','booking offer source is additive');
select col_is_null('public','appointment','booking_option_id','booking option source is additive');
select col_is_null('public','appointment','free_choice_request_id','free choice source is additive');
select has_column('public','free_choice_approval_operation','request_id','operation binds request');
select has_column('public','free_choice_approval_operation','connection_id','operation binds connection');
select has_column('public','free_choice_approval_operation','calendar_id','operation binds calendar');
select has_column('public','free_choice_approval_operation','event_id','operation binds event identity');
select has_column('public','free_choice_approval_operation','correlation','operation binds correlation');
select ok(has_function_privilege('service_role','public.claim_free_choice_owner_approval(uuid,uuid,uuid,text,text,timestamptz)','execute'),'service role may claim approval');
select ok(not has_function_privilege('authenticated','public.claim_free_choice_owner_approval(uuid,uuid,uuid,text,text,timestamptz)','execute'),'authenticated cannot bypass OWNER handler');
select ok(has_function_privilege('service_role','public.reject_free_choice_owner_request(uuid,uuid,uuid,timestamptz)','execute'),'service role may reject');
select ok(not has_function_privilege('anon','public.finalize_free_choice_owner_approval(uuid,uuid,uuid,uuid,uuid,text,text,text,timestamptz)','execute'),'anon cannot finalize');
select * from finish();
rollback;
