/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: f827da729da63f977b60860d00261164)
interface __BaseEnv_Env {
	IMAGES: ImagesBinding;
	INKENDAR_APP_ORIGIN: "https://inkendar-staging.calalva82.workers.dev" | "https://inkendar.calalva82.workers.dev" | "http://127.0.0.1:5173";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./workers/app");
	}
	interface StagingEnv {
		IMAGES: ImagesBinding;
		INKENDAR_APP_ORIGIN: "https://inkendar-staging.calalva82.workers.dev";
	}
	interface ProductionEnv {
		IMAGES: ImagesBinding;
		INKENDAR_APP_ORIGIN: "https://inkendar.calalva82.workers.dev";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "INKENDAR_APP_ORIGIN">> {}
}
