/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 82c2e0deea00c6eb0203184570be40ce)
interface __BaseEnv_Env {
	IMAGES: ImagesBinding;
	INKENDAR_APP_ORIGIN: "https://staging.app.inkendar.es" | "https://app.inkendar.es" | "http://127.0.0.1:5173";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./workers/app");
	}
	interface StagingEnv {
		IMAGES: ImagesBinding;
		INKENDAR_APP_ORIGIN: "https://staging.app.inkendar.es";
	}
	interface ProductionEnv {
		IMAGES: ImagesBinding;
		INKENDAR_APP_ORIGIN: "https://app.inkendar.es";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "INKENDAR_APP_ORIGIN">> {}
}
