import { describe, expect, it, vi } from "vitest";
import { GOOGLE_FREE_BUSY_SCOPE, AvailabilityCredentialInvalidError } from "./availability.js";
import { FreeChoiceAvailabilityUnavailableError, createFreeChoiceAvailabilityService, type FreeChoiceAvailabilityAccessRepositoryPort, type PublicFreeChoiceAvailabilityRepositoryPort } from "./free-choice-availability.js";

const studioId="20000000-0000-4000-8000-000000000001",artistId="50000000-0000-4000-8000-000000000001",now="2026-09-20T08:00:00.000Z",tokenHash="ab".repeat(32);
const access={rangeStart:"2026-09-21T00:00:00.000Z",rangeEnd:"2026-09-22T00:00:00.000Z",durationMinutes:60,expiresAt:"2026-09-21T12:00:00.000Z"};
const rules={timeZone:"Europe/Dublin",windows:[{weekday:1,start:"09:00",end:"12:00"}],slotIncrementMinutes:60,bufferBeforeMinutes:0,bufferAfterMinutes:0};
function setup(scopes:readonly string[]=[GOOGLE_FREE_BUSY_SCOPE]) { const ownerRepository:FreeChoiceAvailabilityAccessRepositoryPort={rotateAccess:vi.fn(async()=>({expiresAt:access.expiresAt}))}; const publicRepository:PublicFreeChoiceAvailabilityRepositoryPort={getContextByTokenHash:vi.fn(async()=>({...access,artistDisplayName:"Ana",rules,calendarId:"artist@test",connection:{status:"ACTIVE" as const,encryptedRefreshToken:"cipher",grantedScopes:scopes,credentialGeneration:3},holds:[{startUtc:"2026-09-21T10:00:00.000Z",endUtc:"2026-09-21T11:00:00.000Z"}]})),markReauthRequired:vi.fn(async()=>undefined)}; const provider={queryBusy:vi.fn(async()=>[{startUtc:"2026-09-21T08:00:00.000Z",endUtc:"2026-09-21T09:00:00.000Z"}])}; const tokens={encrypt:vi.fn(),decrypt:vi.fn(()=>"refresh")}; return {ownerRepository,publicRepository,provider,tokens}; }

describe("free-choice availability service",()=>{
 it("issues a 256-bit token while persistence receives only its hash and bounded configuration",async()=>{const d=setup(),randomBytes=vi.fn(()=>new Uint8Array(32)),hashToken=vi.fn(()=>tokenHash);const service=createFreeChoiceAvailabilityService({...d,randomBytes,hashToken,clock:()=>new Date(now)});const issued=await service.issue(studioId,artistId,access);expect(issued).toEqual({token:expect.stringMatching(/^[A-Za-z0-9_-]{43}$/u),expiresAt:access.expiresAt});expect(d.ownerRepository.rotateAccess).toHaveBeenCalledWith({studioId,artistProfileId:artistId,tokenHash,...access,nowUtc:now});expect(JSON.stringify(vi.mocked(d.ownerRepository.rotateAccess).mock.calls)).not.toContain(issued.token);});
 it("calculates public candidates from FreeBusy plus holds and returns no internal context",async()=>{const d=setup();const service=createFreeChoiceAvailabilityService({...d,randomBytes:vi.fn(),hashToken:()=>tokenHash,clock:()=>new Date(now)});const result=await service.getPublic("A".repeat(43));expect(d.provider.queryBusy).toHaveBeenCalledWith("refresh",{calendarId:"artist@test",timeMin:access.rangeStart,timeMax:access.rangeEnd});expect(result.slots.map(x=>x.startUtc)).toEqual(["2026-09-21T09:00:00.000Z"]);expect(result).toEqual({...access,artistDisplayName:"Ana",timeZone:"Europe/Dublin",slots:[{startUtc:"2026-09-21T09:00:00.000Z",endUtc:"2026-09-21T10:00:00.000Z",startLocal:"2026-09-21T10:00",endLocal:"2026-09-21T11:00"}]});expect(JSON.stringify(result)).not.toMatch(/studio|artistProfile|calendar|connection|token|hash|event|title|description/iu);});
 it.each([undefined,[],["other"]])("fails closed for missing context or FreeBusy scope",async(scopes)=>{const d=setup(scopes??[GOOGLE_FREE_BUSY_SCOPE]);if(scopes===undefined)vi.mocked(d.publicRepository.getContextByTokenHash).mockResolvedValueOnce(null);const service=createFreeChoiceAvailabilityService({...d,randomBytes:vi.fn(),hashToken:()=>tokenHash,clock:()=>new Date(now)});await expect(service.getPublic("A".repeat(43))).rejects.toBeInstanceOf(FreeChoiceAvailabilityUnavailableError);expect(d.tokens.decrypt).not.toHaveBeenCalled();expect(d.provider.queryBusy).not.toHaveBeenCalled();});
 it("marks reconnect with token-bound generation CAS on invalid_grant and still fails generically",async()=>{const d=setup();vi.mocked(d.provider.queryBusy).mockRejectedValueOnce(new AvailabilityCredentialInvalidError());const service=createFreeChoiceAvailabilityService({...d,randomBytes:vi.fn(),hashToken:()=>tokenHash,clock:()=>new Date(now)});await expect(service.getPublic("A".repeat(43))).rejects.toBeInstanceOf(FreeChoiceAvailabilityUnavailableError);expect(d.publicRepository.markReauthRequired).toHaveBeenCalledWith({tokenHash,credentialGeneration:3,nowUtc:now});});
});
