import {describe,expect,it,vi} from "vitest";
import {GOOGLE_FREE_BUSY_SCOPE,type GoogleFreeBusyPort} from "./availability.js";
import {BOOKING_EVENT_SUMMARY,BookingConfirmationMismatchError,BookingConfirmationProviderUnavailableError,BookingConfirmationReconnectRequiredError,GOOGLE_CALENDAR_EVENTS_SCOPE,type BookingCalendarEvent,type GoogleBookingEventPort} from "./booking-confirmation.js";
import {createFreeChoiceOwnerDecisionService,type FreeChoiceOwnerDecisionRepositoryPort,type FreeChoiceApprovalClaim} from "./free-choice-owner-decision.js";
const now="2026-09-18T10:00:00.000Z",requestId="93000000-0000-4000-8000-000000000001",studioId="20000000-0000-4000-8000-000000000001",ownerId="10000000-0000-4000-8000-000000000001",interval={startUtc:"2026-09-21T09:00:00.000Z",endUtc:"2026-09-21T10:00:00.000Z"},identity={eventId:"inkendar0123456789abcdefghijklmnopqrstuv",correlation:"opaque-correlation"};
const connection={id:"81000000-0000-4000-8000-000000000001",status:"ACTIVE" as const,encryptedRefreshToken:"cipher",grantedScopes:[GOOGLE_FREE_BUSY_SCOPE,GOOGLE_CALENDAR_EVENTS_SCOPE],credentialGeneration:7};
const claim:Extract<FreeChoiceApprovalClaim,{kind:"CLAIMED"}>={kind:"CLAIMED",mode:"INSERT_OR_RECONCILE",leaseId:"92000000-0000-4000-8000-000000000001",studioId,requestId,...interval,...identity,calendarId:"artist@example.test",connection,finalized:null};
const event:BookingCalendarEvent={id:identity.eventId,...interval,status:"confirmed",summary:BOOKING_EVENT_SUMMARY,transparency:"opaque",visibility:"private",correlation:identity.correlation,attendeeCount:0};
function setup(){const order:string[]=[];const repository:FreeChoiceOwnerDecisionRepositoryPort={claim:vi.fn(async()=>claim),beginInsert:vi.fn(async()=>{order.push("begin");return true;}),releaseClaim:vi.fn(async()=>undefined),finalize:vi.fn(async()=>({confirmedAt:now})),reject:vi.fn(async()=>({state:"REJECTED" as const})),markReauthRequired:vi.fn(async()=>undefined)};const events:GoogleBookingEventPort={getEvent:vi.fn(async()=>{order.push("get");return null;}),insertEvent:vi.fn(async()=>{order.push("insert");return event;})};const freeBusy:GoogleFreeBusyPort={queryBusy:vi.fn(async()=>{order.push("freebusy");return [];})};return {order,repository,events,freeBusy,tokens:{encrypt:vi.fn(),decrypt:vi.fn(()=>"refresh")},identity:{create:vi.fn(()=>identity)},clock:()=>new Date(now)};}
describe("free-choice OWNER decision",()=>{
 it("rejects idempotently without touching Google",async()=>{const d=setup();await expect(createFreeChoiceOwnerDecisionService(d).reject({studioId,ownerUserId:ownerId,requestId})).resolves.toEqual({state:"REJECTED"});expect(d.repository.reject).toHaveBeenCalledWith({studioId,ownerUserId:ownerId,requestId,nowUtc:now});expect(d.events.getEvent).not.toHaveBeenCalled();});
 it("approves only after get, final FreeBusy and the durable INSERTING fence",async()=>{const d=setup();await expect(createFreeChoiceOwnerDecisionService(d).approve({studioId,ownerUserId:ownerId,requestId})).resolves.toEqual({state:"CONFIRMED",confirmedAt:now});expect(d.order).toEqual(["get","freebusy","begin","insert"]);expect(d.repository.claim).toHaveBeenCalledWith({studioId,ownerUserId:ownerId,requestId,...identity,nowUtc:now});expect(d.events.insertEvent).toHaveBeenCalledWith("refresh",{calendarId:claim.calendarId,...identity,...interval,summary:BOOKING_EVENT_SUMMARY});});
 it("reconciles a lost insert response and never performs a second insert",async()=>{const d=setup();vi.mocked(d.events.insertEvent).mockRejectedValueOnce(new BookingConfirmationProviderUnavailableError());vi.mocked(d.events.getEvent).mockResolvedValueOnce(null).mockResolvedValueOnce(event);await expect(createFreeChoiceOwnerDecisionService(d).approve({studioId,ownerUserId:ownerId,requestId})).resolves.toMatchObject({state:"CONFIRMED"});expect(d.events.insertEvent).toHaveBeenCalledOnce();});
 it("uses Events.get only after INSERTING and fails closed on mismatch",async()=>{const d=setup();vi.mocked(d.repository.claim).mockResolvedValueOnce({...claim,mode:"RECONCILE_ONLY"});await expect(createFreeChoiceOwnerDecisionService(d).approve({studioId,ownerUserId:ownerId,requestId})).rejects.toBeInstanceOf(BookingConfirmationMismatchError);expect(d.freeBusy.queryBusy).not.toHaveBeenCalled();expect(d.events.insertEvent).not.toHaveBeenCalled();});
 it("fails closed before insert when claim reports scopes/config unavailable",async()=>{const d=setup();vi.mocked(d.repository.claim).mockResolvedValueOnce({kind:"RECONNECT_REQUIRED"});await expect(createFreeChoiceOwnerDecisionService(d).approve({studioId,ownerUserId:ownerId,requestId})).rejects.toBeInstanceOf(BookingConfirmationReconnectRequiredError);expect(d.events.getEvent).not.toHaveBeenCalled();});
});
