import {describe,expect,it,vi} from "vitest";
import {GOOGLE_FREE_BUSY_SCOPE,AvailabilityCredentialInvalidError} from "./availability.js";
import {FreeChoiceAvailabilityUnavailableError,createFreeChoiceAvailabilityService,type FreeChoiceAvailabilityAccessRepositoryPort,type PublicFreeChoiceAvailabilityRepositoryPort} from "./free-choice-availability.js";
const studioId="20000000-0000-4000-8000-000000000001",artistId="50000000-0000-4000-8000-000000000001",caseId="60000000-0000-4000-8000-000000000001",now="2026-09-20T08:00:00.000Z",token="A".repeat(43),tokenHash="ab".repeat(32),selector="cd".repeat(32);
const access={rangeStart:"2026-09-21T00:00:00.000Z",rangeEnd:"2026-09-22T00:00:00.000Z",durationMinutes:60,expiresAt:"2026-09-21T12:00:00.000Z"},rules={timeZone:"Europe/Dublin",windows:[{weekday:1,start:"09:00",end:"12:00"}],slotIncrementMinutes:60,bufferBeforeMinutes:0,bufferAfterMinutes:0};
function setup(caseBound=true){
 const ownerRepository:FreeChoiceAvailabilityAccessRepositoryPort={rotateAccess:vi.fn(async()=>({expiresAt:access.expiresAt})),getManagement:vi.fn(async()=>({cases:[],pendingRequests:[]}))};
 const publicRepository:PublicFreeChoiceAvailabilityRepositoryPort={getRequestStatusByTokenHash:vi.fn(async()=>null),getContextByTokenHash:vi.fn(async()=>({...access,caseBound,artistDisplayName:"Ana",rules,calendarId:"artist@test",connection:{status:"ACTIVE" as const,encryptedRefreshToken:"cipher",grantedScopes:[GOOGLE_FREE_BUSY_SCOPE],credentialGeneration:3},holds:[{startUtc:"2026-09-21T10:00:00.000Z",endUtc:"2026-09-21T11:00:00.000Z"}],pendingRequest:null})),selectPending:vi.fn(async(input)=>({state:"PENDING_OWNER_APPROVAL" as const,startUtc:input.startUtc,endUtc:input.endUtc,expiresAt:"2026-09-21T09:00:00.000Z"})),markReauthRequired:vi.fn(async()=>undefined)};
 const provider={queryBusy:vi.fn(async()=>[{startUtc:"2026-09-21T08:00:00.000Z",endUtc:"2026-09-21T09:00:00.000Z"}])},tokens={encrypt:vi.fn(),decrypt:vi.fn(()=>"refresh")};return {ownerRepository,publicRepository,provider,tokens};
}
const service=(d:ReturnType<typeof setup>)=>createFreeChoiceAvailabilityService({...d,randomBytes:()=>new Uint8Array(32),hashToken:(value)=>value===token?tokenHash:selector,clock:()=>new Date(now)});
describe("free-choice availability service",()=>{
 it("issues a hash-only token bound to one case and artist",async()=>{const d=setup(),issued=await service(d).issue(studioId,caseId,artistId,access);expect(issued.token).toMatch(/^[A-Za-z0-9_-]{43}$/u);expect(d.ownerRepository.rotateAccess).toHaveBeenCalledWith({studioId,tattooCaseId:caseId,artistProfileId:artistId,tokenHash,...access,nowUtc:now});expect(JSON.stringify(vi.mocked(d.ownerRepository.rotateAccess).mock.calls)).not.toContain(issued.token);});
 it("returns opaque candidate selectors without private context",async()=>{const d=setup(),result=await service(d).getPublic(token);expect(result.state).toBe("OPEN");if(result.state!=="OPEN")return;expect(result.slots).toEqual([{selector,startUtc:"2026-09-21T09:00:00.000Z",endUtc:"2026-09-21T10:00:00.000Z",startLocal:"2026-09-21T10:00",endLocal:"2026-09-21T11:00"}]);expect(JSON.stringify(result)).not.toMatch(/customer|caseId|studio|calendar|connection|token/iu);});
 it("revalidates FreeBusy before atomically materializing the selected candidate",async()=>{const d=setup(),subject=service(d),view=await subject.getPublic(token);if(view.state!=="OPEN")throw new Error("Expected open");const result=await subject.selectPublic(token,view.slots[0]!.selector);expect(d.provider.queryBusy).toHaveBeenCalledTimes(2);expect(d.publicRepository.selectPending).toHaveBeenCalledWith({tokenHash,selector,startUtc:"2026-09-21T09:00:00.000Z",endUtc:"2026-09-21T10:00:00.000Z",nowUtc:now});expect(result.state).toBe("PENDING_OWNER_APPROVAL");});
 it("denies legacy query-only links on POST",async()=>{const d=setup(false);await expect(service(d).selectPublic(token,selector)).rejects.toBeInstanceOf(FreeChoiceAvailabilityUnavailableError);expect(d.provider.queryBusy).not.toHaveBeenCalled();});
 it("denies stale selectors",async()=>{const d=setup();await expect(service(d).selectPublic(token,"ef".repeat(32))).rejects.toBeInstanceOf(FreeChoiceAvailabilityUnavailableError);expect(d.publicRepository.selectPending).not.toHaveBeenCalled();});
 it("marks reconnect by token generation on invalid_grant",async()=>{const d=setup();vi.mocked(d.provider.queryBusy).mockRejectedValueOnce(new AvailabilityCredentialInvalidError());await expect(service(d).getPublic(token)).rejects.toBeInstanceOf(FreeChoiceAvailabilityUnavailableError);expect(d.publicRepository.markReauthRequired).toHaveBeenCalledWith({tokenHash,credentialGeneration:3,nowUtc:now});}); it.each([
  [{state:"PENDING_OWNER_APPROVAL",startUtc:"2026-09-21T09:00:00.000Z",endUtc:"2026-09-21T10:00:00.000Z"},{state:"PENDING_OWNER_APPROVAL",selectedSlot:{startUtc:"2026-09-21T09:00:00.000Z",endUtc:"2026-09-21T10:00:00.000Z"}}],
  [{state:"APPROVING"},{state:"APPROVING"}],
  [{state:"CONFIRMED",startUtc:"2026-09-21T09:00:00.000Z",endUtc:"2026-09-21T10:00:00.000Z"},{state:"CONFIRMED",selectedSlot:{startUtc:"2026-09-21T09:00:00.000Z",endUtc:"2026-09-21T10:00:00.000Z"}}],
  [{state:"REJECTED"},{state:"REJECTED"}],
  [{state:"EXPIRED"},{state:"EXPIRED"}],
 ])("returns terminal request status without consulting selection authority",async(record,expected)=>{const d=setup();vi.mocked(d.publicRepository.getRequestStatusByTokenHash).mockResolvedValueOnce(record as never);await expect(service(d).getPublic(token)).resolves.toEqual(expected);expect(d.publicRepository.getRequestStatusByTokenHash).toHaveBeenCalledWith({tokenHash,nowUtc:now});expect(d.publicRepository.getContextByTokenHash).not.toHaveBeenCalled();expect(d.provider.queryBusy).not.toHaveBeenCalled();expect(JSON.stringify(expected)).not.toMatch(/artist|customer|case|studio|calendar|requestId/iu);});
});
