import { describe,expect,it,vi } from "vitest";
import { SupabaseFreeChoiceAvailabilityAccessRepository,SupabasePublicFreeChoiceAvailabilityRepository,type FreeChoiceAvailabilityDataGateway } from "./supabase-free-choice-availability.js";

const ownerId="10000000-0000-4000-8000-000000000001",studioId="20000000-0000-4000-8000-000000000001",artistId="50000000-0000-4000-8000-000000000001",tokenHash="ab".repeat(32),now="2026-09-20T08:00:00.000Z";
const access={rangeStart:"2026-09-21T00:00:00.000Z",rangeEnd:"2026-09-22T00:00:00.000Z",durationMinutes:60,expiresAt:"2026-09-21T12:00:00.000Z"};
function gateway():FreeChoiceAvailabilityDataGateway{return {rotateAccess:vi.fn(async()=>({data:{expires_at:access.expiresAt},error:null})),getPublicContext:vi.fn(async()=>({data:{range_start:access.rangeStart,range_end:access.rangeEnd,duration_minutes:60,expires_at:access.expiresAt,artist_display_name:"Ana",time_zone:"Europe/Dublin",slot_increment_minutes:60,buffer_before_minutes:0,buffer_after_minutes:0,windows:[{weekday:1,start_time:"09:00",end_time:"12:00"}],calendar_id:"artist@test",connection:{status:"ACTIVE",refresh_token_ciphertext:"cipher",granted_scopes:["scope"],credential_generation:3},holds:[{start_at:"2026-09-21T10:00:00Z",end_at:"2026-09-21T11:00:00Z"}],studio_id:studioId,artist_profile_id:artistId,event_title:"private"},error:null})),markReauthRequired:vi.fn(async()=>({data:false,error:null}))};}

describe("Supabase free-choice availability",()=>{
 it("binds rotation to OWNER, tenant and hash-only configuration",async()=>{const data=gateway(),repo=new SupabaseFreeChoiceAvailabilityAccessRepository(data,ownerId);await expect(repo.rotateAccess({studioId,artistProfileId:artistId,tokenHash,...access,nowUtc:now})).resolves.toEqual({expiresAt:access.expiresAt});expect(data.rotateAccess).toHaveBeenCalledWith({p_studio_id:studioId,p_owner_user_id:ownerId,p_artist_profile_id:artistId,p_token_hash:tokenHash,p_range_start:access.rangeStart,p_range_end:access.rangeEnd,p_duration_minutes:60,p_expires_at:access.expiresAt,p_now:now});});
 it("maps the server-only context strictly and drops unrelated private fields",async()=>{const data=gateway(),repo=new SupabasePublicFreeChoiceAvailabilityRepository(data);const result=await repo.getContextByTokenHash({tokenHash,nowUtc:now});expect(result).toEqual({...access,artistDisplayName:"Ana",rules:{timeZone:"Europe/Dublin",slotIncrementMinutes:60,bufferBeforeMinutes:0,bufferAfterMinutes:0,windows:[{weekday:1,start:"09:00",end:"12:00"}]},calendarId:"artist@test",connection:{status:"ACTIVE",encryptedRefreshToken:"cipher",grantedScopes:["scope"],credentialGeneration:3},holds:[{startUtc:"2026-09-21T10:00:00.000Z",endUtc:"2026-09-21T11:00:00.000Z"}]});expect(JSON.stringify(result)).not.toMatch(/studio_id|artist_profile_id|event_title/iu);});
 it("binds reconnect CAS to the live token hash and generation",async()=>{const data=gateway(),repo=new SupabasePublicFreeChoiceAvailabilityRepository(data);await repo.markReauthRequired({tokenHash,credentialGeneration:3,nowUtc:now});expect(data.markReauthRequired).toHaveBeenCalledWith({p_token_hash:tokenHash,p_credential_generation:3,p_now:now});});
});
