import {describe,expect,it,vi} from "vitest";
import {BookingConfirmationMismatchError} from "@inkendar/application";
import {SupabaseFreeChoiceOwnerDecisionRepository,type FreeChoiceOwnerDecisionDataGateway} from "./supabase-free-choice-owner-decision.js";

const studioId="20000000-0000-4000-8000-000000000001",ownerUserId="10000000-0000-4000-8000-000000000001",requestId="93000000-0000-4000-8000-000000000001",leaseId="92000000-0000-4000-8000-000000000001",connectionId="81000000-0000-4000-8000-000000000001",now="2026-09-18T10:00:00.000Z",eventId="inkendar012345",correlation="C".repeat(43);
function gateway():FreeChoiceOwnerDecisionDataGateway{return {claim:vi.fn(async()=>({data:{kind:"CLAIMED",mode:"INSERT_OR_RECONCILE",lease_id:leaseId,studio_id:studioId,request_id:requestId,start_at:"2026-09-21T09:00:00Z",end_at:"2026-09-21T10:00:00Z",calendar_id:"artist@example.test",event_id:eventId,correlation,connection:{id:connectionId,status:"ACTIVE",refresh_token_ciphertext:"cipher",granted_scopes:["scope"],credential_generation:7},finalized:null},error:null})),beginInsert:vi.fn(async()=>({data:true,error:null})),releaseClaim:vi.fn(async()=>({data:null,error:null})),finalize:vi.fn(async()=>({data:{confirmed_at:now},error:null})),reject:vi.fn(async()=>({data:{state:"REJECTED"},error:null})),markReauthRequired:vi.fn(async()=>({data:false,error:null}))};}
describe("Supabase free-choice OWNER decision repository",()=>{
 it("maps the OWNER-bound RPC protocol",async()=>{const data=gateway(),repository=new SupabaseFreeChoiceOwnerDecisionRepository(data);await expect(repository.claim({studioId,ownerUserId,requestId,eventId,correlation,nowUtc:now})).resolves.toMatchObject({kind:"CLAIMED",requestId,leaseId,connection:{id:connectionId}});expect(data.claim).toHaveBeenCalledWith({p_studio_id:studioId,p_owner_user_id:ownerUserId,p_request_id:requestId,p_event_id:eventId,p_correlation:correlation,p_now:now});await expect(repository.beginInsert({studioId,ownerUserId,requestId,leaseId,nowUtc:now})).resolves.toBe(true);await repository.releaseClaim({studioId,ownerUserId,requestId,leaseId,nowUtc:now});await expect(repository.finalize({studioId,ownerUserId,requestId,leaseId,connectionId,calendarId:"artist@example.test",eventId,correlation,nowUtc:now})).resolves.toEqual({confirmedAt:now});await expect(repository.reject({studioId,ownerUserId,requestId,nowUtc:now})).resolves.toEqual({state:"REJECTED"});});
 it("maps closed states without bound data",async()=>{for(const kind of ["BUSY","CONFLICT","RECONNECT_REQUIRED","UNAVAILABLE"] as const){const data=gateway();vi.mocked(data.claim).mockResolvedValueOnce({data:{kind,secret:"discard"},error:null});await expect(new SupabaseFreeChoiceOwnerDecisionRepository(data).claim({studioId,ownerUserId,requestId,eventId,correlation,nowUtc:now})).resolves.toEqual({kind});}});
 it("fails closed on malformed data and maps mismatch",async()=>{const data=gateway();vi.mocked(data.claim).mockResolvedValueOnce({data:{kind:"CLAIMED"},error:null});await expect(new SupabaseFreeChoiceOwnerDecisionRepository(data).claim({studioId,ownerUserId,requestId,eventId,correlation,nowUtc:now})).rejects.toThrow("Free-choice decision persistence failed");vi.mocked(data.finalize).mockResolvedValueOnce({data:null,error:{code:"P0003"}});await expect(new SupabaseFreeChoiceOwnerDecisionRepository(data).finalize({studioId,ownerUserId,requestId,leaseId,connectionId,calendarId:"artist@example.test",eventId,correlation,nowUtc:now})).rejects.toBeInstanceOf(BookingConfirmationMismatchError);});
});
