import {createClient} from "@supabase/supabase-js";
import {BookingConfirmationMismatchError,type BookingConfirmationConnection,type FreeChoiceApprovalClaim,type FreeChoiceOwnerDecisionRepositoryPort} from "@inkendar/application";
type Result=Readonly<{data:unknown;error:unknown}>;
export interface FreeChoiceOwnerDecisionDataGateway{claim(parameters:Record<string,unknown>):Promise<Result>;beginInsert(parameters:Record<string,unknown>):Promise<Result>;releaseClaim(parameters:Record<string,unknown>):Promise<Result>;finalize(parameters:Record<string,unknown>):Promise<Result>;reject(parameters:Record<string,unknown>):Promise<Result>;markReauthRequired(parameters:Record<string,unknown>):Promise<Result>;}
export class SupabaseFreeChoiceOwnerDecisionRepository implements FreeChoiceOwnerDecisionRepositoryPort{
 constructor(private readonly data:FreeChoiceOwnerDecisionDataGateway){}
 async claim(input:Parameters<FreeChoiceOwnerDecisionRepositoryPort["claim"]>[0]):Promise<FreeChoiceApprovalClaim>{const result=await this.data.claim(ownerParams(input,{p_event_id:input.eventId,p_correlation:input.correlation}));if(result.error)mismatchOrFail(result.error);const row=object(result.data),kind=string(row.kind);if(kind==="BUSY"||kind==="CONFLICT"||kind==="RECONNECT_REQUIRED"||kind==="UNAVAILABLE")return {kind};if(kind!=="CLAIMED")fail();return {kind,mode:mode(row.mode),leaseId:string(row.lease_id),studioId:string(row.studio_id),requestId:string(row.request_id),startUtc:timestamp(row.start_at),endUtc:timestamp(row.end_at),calendarId:string(row.calendar_id),eventId:string(row.event_id),correlation:string(row.correlation),connection:connection(object(row.connection)),finalized:row.finalized===null?null:finalized(object(row.finalized))};}
 async beginInsert(input:Parameters<FreeChoiceOwnerDecisionRepositoryPort["beginInsert"]>[0]){const result=await this.data.beginInsert(ownerParams(input,{p_lease_id:input.leaseId}));if(result.error||typeof result.data!=="boolean")fail();return result.data;}
 async releaseClaim(input:Parameters<FreeChoiceOwnerDecisionRepositoryPort["releaseClaim"]>[0]){const result=await this.data.releaseClaim(ownerParams(input,{p_lease_id:input.leaseId}));if(result.error)fail();}
 async finalize(input:Parameters<FreeChoiceOwnerDecisionRepositoryPort["finalize"]>[0]){const result=await this.data.finalize(ownerParams(input,{p_lease_id:input.leaseId,p_connection_id:input.connectionId,p_calendar_id:input.calendarId,p_event_id:input.eventId,p_correlation:input.correlation}));if(result.error||result.data===null)mismatchOrFail(result.error);return {confirmedAt:timestamp(object(result.data).confirmed_at)};}
 async reject(input:Parameters<FreeChoiceOwnerDecisionRepositoryPort["reject"]>[0]){const result=await this.data.reject(ownerParams(input));if(result.error||result.data===null)fail();if(object(result.data).state!=="REJECTED")fail();return {state:"REJECTED" as const};}
 async markReauthRequired(studioId:string,connectionId:string,credentialGeneration:number){const result=await this.data.markReauthRequired({p_studio_id:studioId,p_connection_id:connectionId,p_credential_generation:credentialGeneration});if(result.error)fail();}
}
export class SupabaseFreeChoiceOwnerDecisionGateway implements FreeChoiceOwnerDecisionDataGateway{constructor(private readonly rpc:(name:string,parameters:Record<string,unknown>)=>Promise<Result>){}claim=(p:Record<string,unknown>)=>this.rpc("claim_free_choice_owner_approval",p);beginInsert=(p:Record<string,unknown>)=>this.rpc("begin_free_choice_owner_approval_insert",p);releaseClaim=(p:Record<string,unknown>)=>this.rpc("release_free_choice_owner_approval_claim",p);finalize=(p:Record<string,unknown>)=>this.rpc("finalize_free_choice_owner_approval",p);reject=(p:Record<string,unknown>)=>this.rpc("reject_free_choice_owner_request",p);markReauthRequired=(p:Record<string,unknown>)=>this.rpc("mark_booking_confirmation_reauth_required",p);}
export function createSupabaseFreeChoiceOwnerDecisionRepository(environment:Record<string,string|undefined>){const url=environment.SUPABASE_URL?.trim(),key=environment.SUPABASE_SERVICE_ROLE_KEY?.trim();if(!url||!key)fail();const client=createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false}});return new SupabaseFreeChoiceOwnerDecisionRepository(new SupabaseFreeChoiceOwnerDecisionGateway(async(name,parameters)=>{const {data,error}=await client.rpc(name,parameters);return {data,error};}));}
function ownerParams(input:{studioId:string;ownerUserId:string;requestId:string;nowUtc:string},extra:Record<string,unknown>={}){return {p_studio_id:input.studioId,p_owner_user_id:input.ownerUserId,p_request_id:input.requestId,...extra,p_now:input.nowUtc};}
function connection(row:Record<string,unknown>):BookingConfirmationConnection{return {id:string(row.id),status:status(row.status),encryptedRefreshToken:nullable(row.refresh_token_ciphertext),grantedScopes:strings(row.granted_scopes),credentialGeneration:positive(row.credential_generation)};}
function finalized(row:Record<string,unknown>){return {eventId:string(row.event_id),correlation:string(row.correlation),confirmedAt:timestamp(row.confirmed_at)};}
function object(value:unknown):Record<string,unknown>{if(!value||typeof value!=="object"||Array.isArray(value))fail();return value as Record<string,unknown>;}
function string(value:unknown){if(typeof value!=="string"||!value)fail();return value;}
function nullable(value:unknown){return value===null?null:string(value);}
function strings(value:unknown){if(!Array.isArray(value)||value.some(item=>typeof item!=="string"||!item))fail();return value as string[];}
function positive(value:unknown){if(typeof value!=="number"||!Number.isSafeInteger(value)||value<1)fail();return value;}
function timestamp(value:unknown){const date=new Date(string(value));if(!Number.isFinite(date.getTime()))fail();return date.toISOString();}
function status(value:unknown):BookingConfirmationConnection["status"]{if(value!=="ACTIVE"&&value!=="REAUTH_REQUIRED"&&value!=="DISCONNECTED")fail();return value;}
function mode(value:unknown):"INSERT_OR_RECONCILE"|"RECONCILE_ONLY"{if(value!=="INSERT_OR_RECONCILE"&&value!=="RECONCILE_ONLY")fail();return value;}
function mismatchOrFail(error:unknown):never{if(error&&typeof error==="object"&&"code" in error&&(error as {code:unknown}).code==="P0003")throw new BookingConfirmationMismatchError();fail();}
function fail():never{throw new Error("Free-choice decision persistence failed");}
