import { createClient } from "@supabase/supabase-js";
import type { ArtistAvailabilityConfiguration, ArtistAvailabilityRepositoryPort } from "@inkendar/application";
import type { AvailabilityRules } from "@inkendar/domain";
type Result=Readonly<{data:unknown;error:unknown}>;
export interface AvailabilityDataGateway { getConfiguration(parameters:Record<string,unknown>):Promise<Result>; saveRules(parameters:Record<string,unknown>):Promise<Result>; markReauthRequired(parameters:Record<string,unknown>):Promise<Result>; }
export class SupabaseAvailabilityRepository implements ArtistAvailabilityRepositoryPort {
 constructor(private readonly data:AvailabilityDataGateway,private readonly ownerUserId:string){}
 async getConfiguration(studioId:string,artistProfileId:string):Promise<ArtistAvailabilityConfiguration>{const result=await this.data.getConfiguration(this.params(studioId,{p_artist_profile_id:artistProfileId}));if(result.error||!Array.isArray(result.data)||result.data.length!==1)throw new Error("Availability persistence failed");const r=result.data[0] as Record<string,unknown>;return {artistProfileId,calendarId:nullable(r.calendar_id),rules:r.time_zone===null?null:{timeZone:string(r.time_zone),slotIncrementMinutes:number(r.slot_increment_minutes),bufferBeforeMinutes:number(r.buffer_before_minutes),bufferAfterMinutes:number(r.buffer_after_minutes),windows:array(r.windows).map((x)=>{const w=x as Record<string,unknown>;return {weekday:number(w.weekday),start:string(w.start_time).slice(0,5),end:string(w.end_time).slice(0,5)};})},connection:r.connection_id===null?null:{id:string(r.connection_id),studioId,status:status(r.connection_status),encryptedRefreshToken:nullable(r.refresh_token_ciphertext),grantedScopes:array(r.granted_scopes).map(string)}};}
 async saveRules(studioId:string,artistProfileId:string,rules:AvailabilityRules):Promise<void>{const r=await this.data.saveRules(this.params(studioId,{p_artist_profile_id:artistProfileId,p_time_zone:rules.timeZone,p_slot_increment_minutes:rules.slotIncrementMinutes,p_buffer_before_minutes:rules.bufferBeforeMinutes,p_buffer_after_minutes:rules.bufferAfterMinutes,p_windows:rules.windows}));if(r.error)throw new Error("Availability persistence failed");}
 async markReauthRequired(studioId:string):Promise<void>{const r=await this.data.markReauthRequired(this.params(studioId));if(r.error)throw new Error("Availability persistence failed");}
 private params(studioId:string,extra:Record<string,unknown>={}):Record<string,unknown>{return {p_studio_id:studioId,p_owner_user_id:this.ownerUserId,...extra};}
}
export class SupabaseAvailabilityGateway implements AvailabilityDataGateway { constructor(private readonly rpc:(name:string,parameters:Record<string,unknown>)=>Promise<Result>){} getConfiguration(p:Record<string,unknown>){return this.rpc("get_artist_availability_configuration",p);} saveRules(p:Record<string,unknown>){return this.rpc("save_artist_availability_rules",p);} markReauthRequired(p:Record<string,unknown>){return this.rpc("mark_google_calendar_reauth_required",p);} }
function array(v:unknown):unknown[]{if(!Array.isArray(v))throw new Error("Availability persistence failed");return v;} function string(v:unknown):string{if(typeof v!=="string"||!v)throw new Error("Availability persistence failed");return v;} function nullable(v:unknown):string|null{return v===null?null:string(v);} function number(v:unknown):number{if(typeof v!=="number")throw new Error("Availability persistence failed");return v;} function status(v:unknown):"ACTIVE"|"REAUTH_REQUIRED"|"DISCONNECTED"{if(v!=="ACTIVE"&&v!=="REAUTH_REQUIRED"&&v!=="DISCONNECTED")throw new Error("Availability persistence failed");return v;}


export function createSupabaseAvailabilityRepository(environment:Record<string,string|undefined>,ownerUserId:string):SupabaseAvailabilityRepository { const url=environment.SUPABASE_URL?.trim(),key=environment.SUPABASE_SERVICE_ROLE_KEY?.trim(); if(!url||!key)throw new Error("Availability persistence failed"); const client=createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false}}); return new SupabaseAvailabilityRepository(new SupabaseAvailabilityGateway(async(name,parameters)=>{const {data,error}=await client.rpc(name,parameters);return {data,error};}),ownerUserId); }


