import {BookingConfirmationConflictError,BookingConfirmationMismatchError,BookingConfirmationProviderUnavailableError,BookingConfirmationReconnectRequiredError,createFreeChoiceOwnerDecisionService} from "@inkendar/application";
import {AesGcmGoogleTokenProtector,GoogleBookingEventHttpAdapter,GoogleFreeBusyHttpAdapter,NodeBookingEventIdentity,createSupabaseFreeChoiceOwnerDecisionRepository,loadGoogleCalendarConfig,loadGoogleTokenEncryptionKey} from "@inkendar/infrastructure";
import type {AuthorizedAccess} from "@inkendar/domain";
import {authHandlers,isTrustedMutationRequest,type AuthorizedRequestAccess} from "./auth.server.js";
type Service=ReturnType<typeof createFreeChoiceOwnerDecisionService>;
type Dependencies=Readonly<{authorize(request:Request):Promise<Response|AuthorizedRequestAccess>;createService(access:AuthorizedAccess):Service}>;
const defaults:Dependencies={authorize:(request)=>authHandlers.requireRole(request,"OWNER"),createService:()=>{const config=loadGoogleCalendarConfig(process.env);return createFreeChoiceOwnerDecisionService({repository:createSupabaseFreeChoiceOwnerDecisionRepository(process.env),events:new GoogleBookingEventHttpAdapter(config),freeBusy:new GoogleFreeBusyHttpAdapter(config),tokens:new AesGcmGoogleTokenProtector(loadGoogleTokenEncryptionKey(process.env)),identity:new NodeBookingEventIdentity()});}};
export function createOwnerFreeChoiceDecisionHandlers(dependencies:Dependencies=defaults){return {async action(request:Request){if(request.method!=="POST"||!isTrustedMutationRequest(request))return new Response("Solicitud rechazada",{status:403,headers:headers()});const authorization=await dependencies.authorize(request);if(authorization instanceof Response)return authorization;const responseHeaders=headers(authorization.headers);try{const form=await request.formData(),intent=field(form,"intent"),requestId=field(form,"requestId"),input={studioId:authorization.access.studioId,ownerUserId:authorization.access.userId,requestId},service=dependencies.createService(authorization.access);if(intent==="approve")await service.approve(input);else if(intent==="reject")await service.reject(input);else return Response.json({error:"Decisión no válida."},{status:400,headers:responseHeaders});responseHeaders.set("Location","/app/owner/calendars");return new Response(null,{status:303,headers:responseHeaders});}catch(error){if(error instanceof BookingConfirmationConflictError)return Response.json({error:"El hueco ya no está disponible."},{status:409,headers:responseHeaders});if(error instanceof BookingConfirmationReconnectRequiredError)return Response.json({error:"Vuelve a conectar Google Calendar antes de aprobar."},{status:409,headers:responseHeaders});if(error instanceof BookingConfirmationMismatchError)return Response.json({error:"La solicitud requiere revisión manual."},{status:409,headers:responseHeaders});if(error instanceof BookingConfirmationProviderUnavailableError)return Response.json({error:"Google Calendar no está disponible; reintenta con seguridad."},{status:503,headers:responseHeaders});return Response.json({error:"No se pudo completar la decisión."},{status:500,headers:responseHeaders});}}};}
export const ownerFreeChoiceDecisionHandlers=createOwnerFreeChoiceDecisionHandlers();
function field(form:FormData,name:string){const value=form.get(name);if(typeof value!=="string"||!value||value.length>128)throw new Error("invalid input");return value;}
function headers(source?:Headers){const result=new Headers(source);result.set("Cache-Control","private, no-store");return result;}
