import { AvailabilityProviderUnavailableError,FreeChoiceAvailabilityContextNotFoundError,createFreeChoiceAvailabilityService } from "@inkendar/application";
import { InvalidAvailabilityInputError,normalizePublicBookingOfferToken,type AuthorizedAccess } from "@inkendar/domain";
import { AesGcmGoogleTokenProtector,GoogleFreeBusyHttpAdapter,createSupabaseFreeChoiceAvailabilityAccessRepository,createSupabasePublicFreeChoiceAvailabilityRepository,loadGoogleCalendarConfig,loadGoogleTokenEncryptionKey,secureBookingOfferTokenBytes,sha256BookingOfferToken } from "@inkendar/infrastructure";
import { authHandlers,isTrustedMutationRequest,type AuthorizedRequestAccess } from "./auth.server.js";

type Service=ReturnType<typeof createFreeChoiceAvailabilityService>;
type OwnerDependencies=Readonly<{authorize(request:Request):Promise<Response|AuthorizedRequestAccess>;createService(access:AuthorizedAccess):Service}>;
type PublicDependencies=Readonly<{createService():Service}>;
const compose=(ownerUserId:string|null):Service=>createFreeChoiceAvailabilityService({ownerRepository:createSupabaseFreeChoiceAvailabilityAccessRepository(process.env,ownerUserId??"00000000-0000-4000-8000-000000000000"),publicRepository:createSupabasePublicFreeChoiceAvailabilityRepository(process.env),provider:new GoogleFreeBusyHttpAdapter(loadGoogleCalendarConfig(process.env)),tokens:new AesGcmGoogleTokenProtector(loadGoogleTokenEncryptionKey(process.env)),randomBytes:secureBookingOfferTokenBytes,hashToken:sha256BookingOfferToken});
const ownerDefaults:OwnerDependencies={authorize:(request)=>authHandlers.requireRole(request,"OWNER"),createService:(access)=>compose(access.userId)};

export function createOwnerFreeChoiceAvailabilityHandlers(dependencies:OwnerDependencies=ownerDefaults){return {async action(request:Request):Promise<Response>{if(request.method!=="POST"||!isTrustedMutationRequest(request))return new Response("Solicitud rechazada",{status:403,headers:privateHeaders()});const authorization=await dependencies.authorize(request);if(authorization instanceof Response)return authorization;const headers=privateHeaders(authorization.headers);try{const form=await request.formData(),issued=await dependencies.createService(authorization.access).issue(authorization.access.studioId,text(form,"artistProfileId"),{rangeStart:utc(form,"rangeStart"),rangeEnd:utc(form,"rangeEnd"),durationMinutes:integer(form,"durationMinutes"),expiresAt:utc(form,"expiresAt")});const origin=request.headers.get("Origin");if(!origin)throw new InvalidAvailabilityInputError();headers.set("Referrer-Policy","no-referrer");return Response.json({accessUrl:new URL(`/availability/${issued.token}`,origin).toString(),expiresAt:issued.expiresAt},{headers});}catch(error){if(error instanceof InvalidAvailabilityInputError)return Response.json({error:"Revisa el rango, la duración y la caducidad."},{status:400,headers});if(error instanceof FreeChoiceAvailabilityContextNotFoundError)return Response.json({error:"Configura reglas, calendario y permiso FreeBusy para el artista."},{status:409,headers});return Response.json({error:"No se pudo emitir el enlace."},{status:500,headers});}}};}

export function createPublicFreeChoiceAvailabilityHandlers(dependencies:PublicDependencies={createService:()=>compose(null)}){return {async loader(_request:Request,rawToken:string|undefined):Promise<Response>{if(!canonical(rawToken))return unavailable();try{return Response.json(await dependencies.createService().getPublic(rawToken),{headers:publicFreeChoiceAvailabilityHeaders()});}catch(error){if(error instanceof AvailabilityProviderUnavailableError)return new Response("La disponibilidad no está disponible temporalmente.",{status:503,headers:publicFreeChoiceAvailabilityHeaders()});return unavailable();}}};}
export const ownerFreeChoiceAvailabilityHandlers=createOwnerFreeChoiceAvailabilityHandlers();
export const publicFreeChoiceAvailabilityHandlers=createPublicFreeChoiceAvailabilityHandlers();
export function publicFreeChoiceAvailabilityHeaders():Headers{return new Headers({"Cache-Control":"private, no-store","Referrer-Policy":"no-referrer","X-Content-Type-Options":"nosniff","X-Frame-Options":"DENY","X-Robots-Tag":"noindex, nofollow","Content-Security-Policy":"default-src 'self'; base-uri 'none'; object-src 'none'; frame-ancestors 'none'; form-action 'none'"});}
function privateHeaders(source?:Headers){const headers=new Headers(source);headers.set("Cache-Control","private, no-store");return headers;}
function unavailable(){return new Response("Este enlace no está disponible.",{status:404,headers:publicFreeChoiceAvailabilityHeaders()});}
function canonical(value:string|undefined):value is string{if(value===undefined)return false;try{normalizePublicBookingOfferToken(value);return true;}catch{return false;}}
function text(form:FormData,name:string):string{const value=form.get(name);if(typeof value!=="string"||value.length>4096)throw new InvalidAvailabilityInputError();return value.trim();}
function integer(form:FormData,name:string):number{const value=Number(text(form,name));if(!Number.isInteger(value))throw new InvalidAvailabilityInputError();return value;}
function utc(form:FormData,name:string):string{const value=text(form,name),match=/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})$/u.exec(value);if(!match)throw new InvalidAvailabilityInputError();const [,year,month,day,hour,minute]=match,date=new Date(`${value}:00.000Z`);if(!Number.isFinite(date.getTime())||date.getUTCFullYear()!==Number(year)||date.getUTCMonth()+1!==Number(month)||date.getUTCDate()!==Number(day)||date.getUTCHours()!==Number(hour)||date.getUTCMinutes()!==Number(minute))throw new InvalidAvailabilityInputError();return date.toISOString();}
