import {AvailabilityProviderUnavailableError,FreeChoiceAvailabilityContextNotFoundError,createFreeChoiceAvailabilityService} from "@inkendar/application";
import {InvalidAvailabilityInputError,normalizePublicBookingOfferToken,type AuthorizedAccess} from "@inkendar/domain";
import {AesGcmGoogleTokenProtector,GoogleFreeBusyHttpAdapter,createSupabaseFreeChoiceAvailabilityAccessRepository,createSupabasePublicFreeChoiceAvailabilityRepository,loadGoogleCalendarConfig,loadGoogleTokenEncryptionKey,secureBookingOfferTokenBytes,sha256BookingOfferToken} from "@inkendar/infrastructure";
import {authHandlers,isTrustedMutationRequest,type AuthorizedRequestAccess} from "./auth.server.js";

type Service=ReturnType<typeof createFreeChoiceAvailabilityService>;
type OwnerDependencies=Readonly<{authorize(request:Request):Promise<Response|AuthorizedRequestAccess>;createService(access:AuthorizedAccess):Service}>;
type PublicDependencies=Readonly<{createService():Service}>;
const compose=(ownerUserId:string|null):Service=>createFreeChoiceAvailabilityService({ownerRepository:createSupabaseFreeChoiceAvailabilityAccessRepository(process.env,ownerUserId??"00000000-0000-4000-8000-000000000000"),publicRepository:createSupabasePublicFreeChoiceAvailabilityRepository(process.env),provider:new GoogleFreeBusyHttpAdapter(loadGoogleCalendarConfig(process.env)),tokens:new AesGcmGoogleTokenProtector(loadGoogleTokenEncryptionKey(process.env)),randomBytes:secureBookingOfferTokenBytes,hashToken:sha256BookingOfferToken});
const ownerDefaults:OwnerDependencies={authorize:(request)=>authHandlers.requireRole(request,"OWNER"),createService:(access)=>compose(access.userId)};

export function createOwnerFreeChoiceAvailabilityHandlers(dependencies:OwnerDependencies=ownerDefaults){return {
 async loader(request:Request){const authorization=await dependencies.authorize(request);if(authorization instanceof Response)return authorization;try{return Response.json(await dependencies.createService(authorization.access).management(authorization.access.studioId),{headers:privateHeaders(authorization.headers)});}catch{return Response.json({error:"No se pudo cargar la elección libre."},{status:500,headers:privateHeaders(authorization.headers)});}},
 async action(request:Request){if(request.method!=="POST"||!isTrustedMutationRequest(request))return new Response("Solicitud rechazada",{status:403,headers:privateHeaders()});const authorization=await dependencies.authorize(request);if(authorization instanceof Response)return authorization;const headers=privateHeaders(authorization.headers);try{const form=await request.formData(),issued=await dependencies.createService(authorization.access).issue(authorization.access.studioId,text(form,"tattooCaseId"),text(form,"artistProfileId"),{rangeStart:utc(form,"rangeStart"),rangeEnd:utc(form,"rangeEnd"),durationMinutes:integer(form,"durationMinutes"),expiresAt:utc(form,"expiresAt")});const origin=request.headers.get("Origin");if(!origin)throw new InvalidAvailabilityInputError();headers.set("Referrer-Policy","no-referrer");return Response.json({accessUrl:new URL(`/availability/${issued.token}`,origin).toString(),expiresAt:issued.expiresAt},{headers});}catch(error){if(error instanceof InvalidAvailabilityInputError)return Response.json({error:"Revisa el caso, rango, duración y caducidad."},{status:400,headers});if(error instanceof FreeChoiceAvailabilityContextNotFoundError)return Response.json({error:"El caso abierto debe estar asignado al artista y tener calendario compatible."},{status:409,headers});return Response.json({error:"No se pudo emitir el enlace."},{status:500,headers});}}
};}

export function createPublicFreeChoiceAvailabilityHandlers(dependencies:PublicDependencies={createService:()=>compose(null)}){return {
 async loader(_request:Request,rawToken:string|undefined){if(!canonical(rawToken))return unavailable();try{return Response.json(await dependencies.createService().getPublic(rawToken),{headers:publicFreeChoiceAvailabilityHeaders()});}catch(error){return error instanceof AvailabilityProviderUnavailableError?temporarilyUnavailable():unavailable();}},
 async action(request:Request,rawToken:string|undefined){if(request.method!=="POST"||!canonical(rawToken)||!isTrustedMutationRequest(request)||request.headers.get("content-type")?.split(";",1)[0]!=="application/x-www-form-urlencoded")return unavailable();const length=Number(request.headers.get("content-length"));if(Number.isFinite(length)&&length>256)return unavailable();try{const body=await request.text();if(body.length>256)return unavailable();const params=new URLSearchParams(body);if([...params.keys()].length!==1||!params.has("selector"))return unavailable();return Response.json(await dependencies.createService().selectPublic(rawToken,params.get("selector")??""),{headers:publicFreeChoiceAvailabilityHeaders()});}catch(error){return error instanceof AvailabilityProviderUnavailableError?temporarilyUnavailable():unavailable();}}
};}
export const ownerFreeChoiceAvailabilityHandlers=createOwnerFreeChoiceAvailabilityHandlers();
export const publicFreeChoiceAvailabilityHandlers=createPublicFreeChoiceAvailabilityHandlers();
export function publicFreeChoiceAvailabilityHeaders(){return new Headers({"Cache-Control":"private, no-store","Referrer-Policy":"no-referrer","X-Content-Type-Options":"nosniff","X-Frame-Options":"DENY","X-Robots-Tag":"noindex, nofollow","Content-Security-Policy":"default-src 'self'; base-uri 'none'; object-src 'none'; frame-ancestors 'none'; form-action 'self'"});}
function privateHeaders(source?:Headers){const headers=new Headers(source);headers.set("Cache-Control","private, no-store");return headers;}
function unavailable(){return new Response("Este enlace no está disponible.",{status:404,headers:publicFreeChoiceAvailabilityHeaders()});}
function temporarilyUnavailable(){return new Response("La disponibilidad no está disponible temporalmente.",{status:503,headers:publicFreeChoiceAvailabilityHeaders()});}
function canonical(value:string|undefined):value is string{if(value===undefined)return false;try{normalizePublicBookingOfferToken(value);return true;}catch{return false;}}
function text(form:FormData,name:string){const value=form.get(name);if(typeof value!=="string"||value.length>4096)throw new InvalidAvailabilityInputError();return value.trim();}
function integer(form:FormData,name:string){const value=Number(text(form,name));if(!Number.isInteger(value))throw new InvalidAvailabilityInputError();return value;}
function utc(form:FormData,name:string){const value=text(form,name),match=/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})$/u.exec(value);if(!match)throw new InvalidAvailabilityInputError();const [,year,month,day,hour,minute]=match,date=new Date(`${value}:00.000Z`);if(!Number.isFinite(date.getTime())||date.getUTCFullYear()!==Number(year)||date.getUTCMonth()+1!==Number(month)||date.getUTCDate()!==Number(day)||date.getUTCHours()!==Number(hour)||date.getUTCMinutes()!==Number(minute))throw new InvalidAvailabilityInputError();return date.toISOString();}
