import { renderToStaticMarkup } from "react-dom/server";
import { createStaticHandler,createStaticRouter,StaticRouterProvider } from "react-router";
import { describe,expect,it,vi } from "vitest";
const handler=vi.hoisted(()=>({loader:vi.fn()}));
vi.mock("./free-choice-availability.server.js",()=>({publicFreeChoiceAvailabilityHandlers:handler,publicFreeChoiceAvailabilityHeaders:()=>new Headers({"Cache-Control":"private, no-store","Referrer-Policy":"no-referrer"})}));
import PublicFreeChoiceAvailability,{ErrorBoundary,loader} from "./routes/public-availability.js";
const routes=[{id:"availability",path:"availability/:token",loader:loader as never,Component:PublicFreeChoiceAvailability,ErrorBoundary}];
describe("public free-choice availability route",()=>{
 it("renders candidates as subject to OWNER approval without leaking internals or offering selection",async()=>{handler.loader.mockResolvedValueOnce(Response.json({rangeStart:"2026-09-21T00:00:00.000Z",rangeEnd:"2026-09-22T00:00:00.000Z",durationMinutes:60,expiresAt:"2026-09-21T12:00:00.000Z",artistDisplayName:"Ana",timeZone:"Europe/Dublin",slots:[{startUtc:"2026-09-21T09:00:00.000Z",endUtc:"2026-09-21T10:00:00.000Z",startLocal:"2026-09-21T10:00",endLocal:"2026-09-21T11:00"}]}));const {query,dataRoutes}=createStaticHandler(routes);const result=await query(new Request(`https://app.inkendar.es/availability/${"A".repeat(43)}`));if(result instanceof Response)throw new Error("Expected context");const html=renderToStaticMarkup(<StaticRouterProvider router={createStaticRouter(dataRoutes,result)} context={result}/>);expect(html).toContain("Huecos disponibles");expect(html).toContain("Ana");expect(html).toContain("Europe/Dublin");expect(html).toContain("requiere aprobación del estudio");expect(html).not.toMatch(/<form|button|selector|customer|case|calendar|token|event|title/iu);});
 it("renders a generic unavailable state",async()=>{handler.loader.mockResolvedValueOnce(new Response("private detail",{status:404}));const {query,dataRoutes}=createStaticHandler(routes);const result=await query(new Request(`https://app.inkendar.es/availability/${"B".repeat(43)}`));if(result instanceof Response)throw new Error("Expected context");const html=renderToStaticMarkup(<StaticRouterProvider router={createStaticRouter(dataRoutes,result)} context={result}/>);expect(html).toContain("Este enlace no está disponible");expect(html).not.toContain("private detail");});
});
