import { describe,expect,it,vi } from "vitest";
import { AvailabilityProviderUnavailableError,FreeChoiceAvailabilityUnavailableError } from "@inkendar/application";
import { createOwnerFreeChoiceAvailabilityHandlers,createPublicFreeChoiceAvailabilityHandlers } from "./free-choice-availability.server.js";

const access={displayName:"Owner",role:"OWNER" as const,studioId:"20000000-0000-4000-8000-000000000001",userId:"10000000-0000-4000-8000-000000000001"},artistId="50000000-0000-4000-8000-000000000001",token="A".repeat(43);
function form(){return new URLSearchParams({artistProfileId:artistId,rangeStart:"2026-09-21T00:00",rangeEnd:"2026-09-22T00:00",durationMinutes:"60",expiresAt:"2026-09-21T12:00"});}

describe("OWNER free-choice availability handler",()=>{
 it("issues a same-origin path URL only after OWNER authorization",async()=>{const issue=vi.fn(async()=>({token,expiresAt:"2026-09-21T12:00:00.000Z"})),createService=vi.fn(()=>({issue,getPublic:vi.fn()}));const handlers=createOwnerFreeChoiceAvailabilityHandlers({authorize:async()=>({access,headers:new Headers()}),createService});const response=await handlers.action(new Request("https://app.inkendar.es/app/owner/calendars?freeChoice=1",{method:"POST",headers:{Origin:"https://app.inkendar.es","Sec-Fetch-Site":"same-origin"},body:form()}));expect(response.status).toBe(200);await expect(response.json()).resolves.toEqual({accessUrl:`https://app.inkendar.es/availability/${token}`,expiresAt:"2026-09-21T12:00:00.000Z"});expect(issue).toHaveBeenCalledWith(access.studioId,artistId,{rangeStart:"2026-09-21T00:00:00.000Z",rangeEnd:"2026-09-22T00:00:00.000Z",durationMinutes:60,expiresAt:"2026-09-21T12:00:00.000Z"});expect(response.headers.get("Referrer-Policy")).toBe("no-referrer");});
 it("denies ARTIST/anonymous and cross-origin before privileged composition",async()=>{const createService=vi.fn();const denied=createOwnerFreeChoiceAvailabilityHandlers({authorize:async()=>new Response("Denied",{status:403}),createService});expect((await denied.action(new Request("https://app.inkendar.es/app/owner/calendars?freeChoice=1",{method:"POST",headers:{Origin:"https://app.inkendar.es","Sec-Fetch-Site":"same-origin"},body:form()}))).status).toBe(403);const cross=createOwnerFreeChoiceAvailabilityHandlers({authorize:vi.fn(),createService});expect((await cross.action(new Request("https://app.inkendar.es/app/owner/calendars?freeChoice=1",{method:"POST",headers:{Origin:"https://evil.test"},body:form()}))).status).toBe(403);expect(createService).not.toHaveBeenCalled();});
});

describe("public free-choice availability handler",()=>{
 it("returns only the public view with defensive headers",async()=>{const view={rangeStart:"2026-09-21T00:00:00.000Z",rangeEnd:"2026-09-22T00:00:00.000Z",durationMinutes:60,expiresAt:"2026-09-21T12:00:00.000Z",artistDisplayName:"Ana",timeZone:"Europe/Dublin",slots:[]};const getPublic=vi.fn(async()=>view),response=await createPublicFreeChoiceAvailabilityHandlers({createService:()=>({issue:vi.fn(),getPublic})}).loader(new Request(`https://app.inkendar.es/availability/${token}`),token);expect(await response.json()).toEqual(view);expect(response.headers.get("Cache-Control")).toBe("private, no-store");expect(response.headers.get("Content-Security-Policy")).toContain("frame-ancestors 'none'");});
 it("uses one generic 404 for malformed, rotated, expired or incompatible access",async()=>{const createService=vi.fn();const handlers=createPublicFreeChoiceAvailabilityHandlers({createService});expect((await handlers.loader(new Request("https://app.inkendar.es/availability/redacted"),"bad")).status).toBe(404);expect(createService).not.toHaveBeenCalled();const unavailable=createPublicFreeChoiceAvailabilityHandlers({createService:()=>({issue:vi.fn(),getPublic:vi.fn(async()=>{throw new FreeChoiceAvailabilityUnavailableError();})})});expect((await unavailable.loader(new Request(`https://app.inkendar.es/availability/${token}`),token)).status).toBe(404);});
 it("maps provider outages to a generic 503 without leaking details",async()=>{const handlers=createPublicFreeChoiceAvailabilityHandlers({createService:()=>({issue:vi.fn(),getPublic:vi.fn(async()=>{throw new AvailabilityProviderUnavailableError();})})});const response=await handlers.loader(new Request(`https://app.inkendar.es/availability/${token}`),token);expect(response.status).toBe(503);expect(await response.text()).toBe("La disponibilidad no está disponible temporalmente.");});
});
