import {describe,expect,it,vi} from "vitest";
import {createOwnerFreeChoiceAvailabilityHandlers,createPublicFreeChoiceAvailabilityHandlers} from "./free-choice-availability.server.js";
const access={displayName:"Owner",role:"OWNER" as const,studioId:"20000000-0000-4000-8000-000000000001",userId:"10000000-0000-4000-8000-000000000001"},artistId="50000000-0000-4000-8000-000000000001",caseId="60000000-0000-4000-8000-000000000001",token="A".repeat(43),selector="ab".repeat(32);
const service=()=>({management:vi.fn(async()=>({cases:[],pendingRequests:[]})),issue:vi.fn(async()=>({token,expiresAt:"2026-09-21T12:00:00.000Z"})),getPublic:vi.fn(),selectPublic:vi.fn(async()=>({state:"PENDING_OWNER_APPROVAL"}))});
describe("free-choice HTTP boundaries",()=>{
 it("issues only for an explicit case under OWNER same-origin",async()=>{const subject=service(),response=await createOwnerFreeChoiceAvailabilityHandlers({authorize:async()=>({access,headers:new Headers()}),createService:()=>subject as never}).action(new Request("https://app.inkendar.es/app/owner/calendars?freeChoice=1",{method:"POST",headers:{Origin:"https://app.inkendar.es","Sec-Fetch-Site":"same-origin"},body:new URLSearchParams({tattooCaseId:caseId,artistProfileId:artistId,rangeStart:"2026-09-21T00:00",rangeEnd:"2026-09-22T00:00",durationMinutes:"60",expiresAt:"2026-09-21T12:00"})}));expect(response.status).toBe(200);expect(subject.issue).toHaveBeenCalledWith(access.studioId,caseId,artistId,expect.any(Object));});
 it("denies anonymous and cross-origin before composition",async()=>{const createService=vi.fn(),handlers=createOwnerFreeChoiceAvailabilityHandlers({authorize:async()=>new Response("Denied",{status:403}),createService});expect((await handlers.action(new Request("https://app.inkendar.es/app/owner/calendars",{method:"POST",headers:{Origin:"https://app.inkendar.es","Sec-Fetch-Site":"same-origin"}}))).status).toBe(403);expect(createService).not.toHaveBeenCalled();});
 it("accepts a bounded same-origin selector-only POST",async()=>{const subject=service(),response=await createPublicFreeChoiceAvailabilityHandlers({createService:()=>subject as never}).action(new Request(`https://app.inkendar.es/availability/${token}`,{method:"POST",headers:{Origin:"https://app.inkendar.es","Sec-Fetch-Site":"same-origin","Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({selector})}),token);expect(response.status).toBe(200);expect(subject.selectPublic).toHaveBeenCalledWith(token,selector);expect(response.headers.get("Cache-Control")).toBe("private, no-store");});
 it("rejects extra fields, cross-origin and malformed tokens generically",async()=>{const subject=service(),handlers=createPublicFreeChoiceAvailabilityHandlers({createService:()=>subject as never});for(const request of [new Request(`https://app.inkendar.es/availability/${token}`,{method:"POST",headers:{Origin:"https://evil.test","Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({selector})}),new Request(`https://app.inkendar.es/availability/${token}`,{method:"POST",headers:{Origin:"https://app.inkendar.es","Sec-Fetch-Site":"same-origin","Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({selector,caseId})})])expect((await handlers.action(request,token)).status).toBe(404);expect(subject.selectPublic).not.toHaveBeenCalled();});
});
