import { AvailabilityProviderUnavailableError, AvailabilitySetupRequiredError, createArtistAvailabilityService } from "@inkendar/application";
import { AesGcmGoogleTokenProtector, GoogleFreeBusyHttpAdapter, createSupabaseAvailabilityRepository, loadGoogleCalendarConfig, loadGoogleTokenEncryptionKey } from "@inkendar/infrastructure";
import { InvalidAvailabilityInputError, type AuthorizedAccess } from "@inkendar/domain";
import { authHandlers, isTrustedMutationRequest, type AuthorizedRequestAccess } from "./auth.server.js";
type Service=ReturnType<typeof createArtistAvailabilityService>;
type Deps=Readonly<{authorize(request:Request):Promise<Response|AuthorizedRequestAccess>;createService(access:AuthorizedAccess):Service}>;
const defaults:Deps={authorize:(request)=>authHandlers.requireRole(request,"OWNER"),createService:(access)=>compose(access,process.env)};
export function createOwnerAvailabilityHandlers(deps:Deps=defaults){return {
 async loader(request:Request):Promise<Response>{const auth=await deps.authorize(request);if(auth instanceof Response)return auth;const artistIds=[...new Set(new URL(request.url).searchParams.getAll("artistProfileId"))];if(artistIds.length>100)return Response.json({error:"Demasiados artistas."},{status:400,headers:headers(auth.headers)});try{const service=deps.createService(auth.access);const entries=await Promise.all(artistIds.map(async(artistId)=>[artistId,await service.getRules(auth.access.studioId,artistId)] as const));return Response.json({availabilityByArtist:Object.fromEntries(entries)},{headers:headers(auth.headers)});}catch{return Response.json({error:"No se pudo cargar la disponibilidad."},{status:400,headers:headers(auth.headers)});}},
 async action(request:Request):Promise<Response>{if(request.method!=="POST"||!isTrustedMutationRequest(request))return new Response("Solicitud rechazada",{status:403,headers:headers()});const auth=await deps.authorize(request);if(auth instanceof Response)return auth;try{const form=await request.formData(),intent=text(form,"intent"),artistId=text(form,"artistProfileId"),service=deps.createService(auth.access);if(intent==="save-availability"){await service.saveRules(auth.access.studioId,artistId,{timeZone:text(form,"timeZone"),slotIncrementMinutes:integer(form,"slotIncrementMinutes"),bufferBeforeMinutes:integer(form,"bufferBeforeMinutes"),bufferAfterMinutes:integer(form,"bufferAfterMinutes"),windows:windows(text(form,"windows"))});return Response.json({saved:true},{headers:headers(auth.headers)});}if(intent==="preview-availability"){const slots=await service.preview(auth.access.studioId,artistId,utc(text(form,"rangeStart")),utc(text(form,"rangeEnd")),integer(form,"durationMinutes"));return Response.json({slots},{headers:headers(auth.headers)});}throw new InvalidAvailabilityInputError();}catch(error){const h=headers(auth.headers);if(error instanceof AvailabilitySetupRequiredError)return Response.json({error:error.reason==="RECONNECT"?"Reconecta Google Calendar para conceder disponibilidad.":error.reason==="NO_CALENDAR"?"Asigna un calendario al artista.":"Guarda reglas de disponibilidad primero."},{status:409,headers:h});if(error instanceof AvailabilityProviderUnavailableError)return Response.json({error:"Google Calendar no está disponible temporalmente."},{status:503,headers:h});return Response.json({error:"Revisa las reglas y el rango."},{status:400,headers:h});}}
};}
export const ownerAvailabilityHandlers=createOwnerAvailabilityHandlers();
function compose(access:AuthorizedAccess,env:Record<string,string|undefined>):Service{return createArtistAvailabilityService({repository:createSupabaseAvailabilityRepository(env,access.userId),provider:new GoogleFreeBusyHttpAdapter(loadGoogleCalendarConfig(env)),tokens:new AesGcmGoogleTokenProtector(loadGoogleTokenEncryptionKey(env))});}
function headers(source?:Headers){const h=new Headers(source);h.set("Cache-Control","private, no-store");return h;} function text(f:FormData,n:string){const v=f.get(n);if(typeof v!=="string"||v.length>4096)throw new InvalidAvailabilityInputError();return v.trim();} function integer(f:FormData,n:string){const v=Number(text(f,n));if(!Number.isInteger(v))throw new InvalidAvailabilityInputError();return v;} function windows(value:string){const result=value.split(/\r?\n/u).filter(Boolean).map(line=>{const [weekday,start,end,...rest]=line.split(",").map(x=>x.trim());if(rest.length||weekday===undefined||start===undefined||end===undefined)throw new InvalidAvailabilityInputError();return {weekday:Number(weekday),start,end};});if(result.length>28)throw new InvalidAvailabilityInputError();return result;}
function utc(value:string):string { const match=/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})$/u.exec(value); if(!match)throw new InvalidAvailabilityInputError(); const [,year,month,day,hour,minute]=match; const date=new Date(`${value}:00Z`); if(!Number.isFinite(date.getTime())||date.getUTCFullYear()!==Number(year)||date.getUTCMonth()+1!==Number(month)||date.getUTCDate()!==Number(day)||date.getUTCHours()!==Number(hour)||date.getUTCMinutes()!==Number(minute))throw new InvalidAvailabilityInputError(); return date.toISOString(); }
